using System.Net;
using System.Text;

namespace Ozakboy.Line.AspNetCore.Tests.TestSupport;

/// <summary>
/// 代替認證處理器的後端通道,依請求位址回傳事先安排好的內容。
/// Stands in for the authentication handler's backchannel, answering by request address.
/// </summary>
/// <remarks>
/// 測試一律離線,LINE 的真實端點一次都不會被打到。
/// The tests are entirely offline; LINE's real endpoints are never called.
/// </remarks>
internal sealed class FakeBackchannelHandler : HttpMessageHandler
{
    private readonly Func<HttpRequestMessage, HttpResponseMessage> _responder;

    /// <summary>
    /// 以自訂的回應邏輯建立。
    /// Creates one with custom response logic.
    /// </summary>
    /// <param name="responder">依請求決定回應。Decides the response from the request.</param>
    internal FakeBackchannelHandler(Func<HttpRequestMessage, HttpResponseMessage> responder) => _responder = responder;

    /// <summary>
    /// 送出過的請求位址。
    /// The addresses that were requested.
    /// </summary>
    internal List<string> Requests { get; } = [];

    /// <summary>
    /// 送出過的請求內容,與 <see cref="Requests"/> 一一對應;沒有內容時為 <see langword="null"/>。
    /// The bodies that were sent, one per entry in <see cref="Requests"/>, or <see langword="null"/> where there
    /// was none.
    /// </summary>
    /// <remarks>
    /// 權杖端點的 <c>redirect_uri</c> 只在請求內容裡看得到,位址上沒有 —— 而那個值正是
    /// <c>PublicOrigin</c> 要影響的東西。
    /// The token endpoint's <c>redirect_uri</c> is visible only in the body and never in the address, and that
    /// value is exactly what <c>PublicOrigin</c> exists to change.
    /// </remarks>
    internal List<string?> Bodies { get; } = [];

    /// <summary>
    /// 權杖端點要回的 id_token;不回時為 <see langword="null"/>。
    /// The id_token the token endpoint answers with, or <see langword="null"/> for none.
    /// </summary>
    /// <remarks>
    /// 這個值可以在挑戰之後、回呼之前改。id_token 裡的 nonce 必須等於挑戰網址上送出的那一個,
    /// 而那個 nonce 是處理器當場產生的 —— 測試只能等看到挑戰網址才知道要簽什麼。
    /// It is settable between the challenge and the callback: the nonce inside the id_token has to match the one
    /// on the challenge URL, and that nonce is generated by the handler on the spot, so a test cannot know what
    /// to sign until it has seen the challenge.
    /// </remarks>
    internal string? IdToken { get; set; }

    /// <summary>
    /// 安排權杖、個人檔案與好友狀態三個端點的回應。
    /// Arranges the token, profile, and friendship endpoints.
    /// </summary>
    /// <param name="idToken">要放進權杖回應的 id_token;不放時為 <see langword="null"/>。The id_token to include, or <see langword="null"/> for none.</param>
    /// <param name="friendFlag">好友狀態端點要回的值。What the friendship endpoint answers.</param>
    /// <param name="friendshipStatusCode">好友狀態端點的狀態碼。The friendship endpoint's status code.</param>
    /// <returns>處理器。The handler.</returns>
    internal static FakeBackchannelHandler ForLogin(
        string? idToken,
        bool friendFlag = true,
        HttpStatusCode friendshipStatusCode = HttpStatusCode.OK)
    {
        FakeBackchannelHandler handler = null!;
        handler = new FakeBackchannelHandler(request =>
        {
            var uri = request.RequestUri!.ToString();

            if (uri.Contains("/oauth2/v2.1/token", StringComparison.Ordinal))
            {
                var idTokenField = handler.IdToken is null ? string.Empty : $",\"id_token\":\"{handler.IdToken}\"";
                return Json($$"""
                    {"access_token":"at-1","expires_in":2592000,"refresh_token":"rt-1","scope":"profile openid","token_type":"Bearer"{{idTokenField}}}
                    """);
            }

            if (uri.Contains("/v2/profile", StringComparison.Ordinal))
            {
                return Json("""{"userId":"U1","displayName":"阿明","pictureUrl":"https://example.com/p.jpg","statusMessage":"今天也很好"}""");
            }

            if (uri.Contains("/friendship/v1/status", StringComparison.Ordinal))
            {
                return friendshipStatusCode == HttpStatusCode.OK
                    ? Json($"{{\"friendFlag\":{(friendFlag ? "true" : "false")}}}")
                    : new HttpResponseMessage(friendshipStatusCode)
                    {
                        Content = new StringContent("""{"message":"not available"}""", Encoding.UTF8, "application/json"),
                    };
            }

            return new HttpResponseMessage(HttpStatusCode.NotFound);
        })
        {
            IdToken = idToken,
        };

        return handler;
    }

    /// <inheritdoc />
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        Requests.Add(request.RequestUri!.ToString());
        Bodies.Add(request.Content is null
            ? null
            : await request.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false));

        return _responder(request);
    }

    /// <summary>
    /// 建立 JSON 回應。
    /// Builds a JSON response.
    /// </summary>
    /// <param name="json">內容。The body.</param>
    /// <returns>回應。The response.</returns>
    private static HttpResponseMessage Json(string json) => new(HttpStatusCode.OK)
    {
        Content = new StringContent(json, Encoding.UTF8, "application/json"),
    };
}
